JQUERY CDN

<script
  src="https://code.jquery.com/jquery-2.2.4.js"
  integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
  crossorigin="anonymous"></script>

  openssl dgst -sha384 -binary FILENAME.js | openssl base64 -A srI 


  import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import 'bootstrap/dist/css/bootstrap.min.css';

ReactDOM.render(<App />, document.getElementById('root'));




//Open the src/OmdbContainer.js and add the following code:


//Add a componentDidMount method which should utilize the API.js module to query the OMDB API for the movie "The Matrix" 

//when the component mounts. Then update this component's result state with the result of the AJAX request. You can verify you 

// completed this step correctly by refreshing the page in your web browser. If successful, the application should display 

// information about the movie "The Matrix" when the page first loads.





// Add a handleInputChange method which should be called whenever the user types into the input field. Inside of this method, set

//  this.state.search equal to the new value of the input field. You can verify you've completed this step correctly if you can 

//  now type into the input field.


// Add a handleFormSubmit method which should be called when the form is submitted. Inside of this method, utilize the API 
// module to search the OMDB API for the value of this.state.search. Then update this component's result state with the result. You can verify you completed this step correctly by searching for the name of a movie. If successful, you should see the movie poster and some information about the movie appear in the left card.

Don't forget to call event.preventDefault() inside of any event handlers called in response to an HTML form being submitted.


